version: "3"

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    container_name: sample_nginx
    networks:
      - laravel
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sample_php
    volumes:
      - ./src:/var/www/html
      - ./docker/php/openssl.cnf:/etc/ssl/openssl.cnf
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql
    container_name: sample_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample_pj
      MYSQL_USER: sample_pj_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel